Repository AY2425S2-CS2103T-T15-4/tp, pull requests merged in 2025-04, with the labels that each got.

#59 build: enable assertions for alpha testing
  build.gradle
Labels: priority.High

#78 Fix all checkStyle issue with Property class
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/property/Location.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/Status.java
  src/main/java/seedu/address/model/property/Type.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
Labels: alpha-bug

#77 Fixed some JsonAdapted files so that they return null if empty instead of something like District(null). Also fixed some javadocs.
  src/main/java/seedu/address/model/person/exceptions/InvalidPredicateException.java
  src/main/java/seedu/address/storage/JsonAdaptedClientType.java
  src/main/java/seedu/address/storage/JsonAdaptedDistrict.java
  src/main/java/seedu/address/storage/JsonAdaptedLandSize.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPrice.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
Labels: type.Bug

#92 Update UG and DG with Property class
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#154 Edited a bunch of stuff to try and get checkstyle working right. I ma…
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/match_1.png
  docs/images/match_2.png
  docs/images/match_initial.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UniquePropertyList.java
  src/main/java/seedu/address/model/person/exceptions/InvalidPredicateException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
Labels: priority.High
